# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 717)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.tab_widget = QtWidgets.QTabWidget(self.splitter_2)
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_widget.setElideMode(QtCore.Qt.ElideNone)
        self.tab_widget.setDocumentMode(False)
        self.tab_widget.setTabsClosable(False)
        self.tab_widget.setMovable(True)
        self.tab_widget.setTabBarAutoHide(False)
        self.tab_widget.setObjectName("tab_widget")
        self.tab_cam = QtWidgets.QWidget()
        self.tab_cam.setObjectName("tab_cam")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_cam)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.tab_cam)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 285, 705))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_5)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 3, 0, 1, 1)
        self.sb_grid_width = QtWidgets.QSpinBox(self.groupBox_2)
        self.sb_grid_width.setMinimum(3)
        self.sb_grid_width.setMaximum(20)
        self.sb_grid_width.setProperty("value", 6)
        self.sb_grid_width.setObjectName("sb_grid_width")
        self.gridLayout_4.addWidget(self.sb_grid_width, 3, 1, 1, 1)
        self.pb_calib_intrinsic = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_calib_intrinsic.setObjectName("pb_calib_intrinsic")
        self.gridLayout_4.addWidget(self.pb_calib_intrinsic, 5, 0, 1, 2)
        self.sb_delay_intrinsic = QtWidgets.QSpinBox(self.groupBox_2)
        self.sb_delay_intrinsic.setProperty("value", 5)
        self.sb_delay_intrinsic.setObjectName("sb_delay_intrinsic")
        self.gridLayout_4.addWidget(self.sb_delay_intrinsic, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.sb_num_of_pics = QtWidgets.QSpinBox(self.groupBox_2)
        self.sb_num_of_pics.setMinimum(10)
        self.sb_num_of_pics.setProperty("value", 30)
        self.sb_num_of_pics.setObjectName("sb_num_of_pics")
        self.gridLayout_4.addWidget(self.sb_num_of_pics, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 4, 0, 1, 1)
        self.sb_grid_height = QtWidgets.QSpinBox(self.groupBox_2)
        self.sb_grid_height.setMinimum(3)
        self.sb_grid_height.setMaximum(20)
        self.sb_grid_height.setProperty("value", 9)
        self.sb_grid_height.setObjectName("sb_grid_height")
        self.gridLayout_4.addWidget(self.sb_grid_height, 4, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_save_intrinsic = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_save_intrinsic.setObjectName("pb_save_intrinsic")
        self.horizontalLayout.addWidget(self.pb_save_intrinsic)
        self.pb_load_intrinsic = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_load_intrinsic.setObjectName("pb_load_intrinsic")
        self.horizontalLayout.addWidget(self.pb_load_intrinsic)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.gridLayout_9.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.combo_box_camera = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.combo_box_camera.setObjectName("combo_box_camera")
        self.gridLayout_9.addWidget(self.combo_box_camera, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_5)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_camera_matrix = QtWidgets.QLabel(self.groupBox_3)
        self.label_camera_matrix.setLineWidth(1)
        self.label_camera_matrix.setTextFormat(QtCore.Qt.RichText)
        self.label_camera_matrix.setObjectName("label_camera_matrix")
        self.verticalLayout.addWidget(self.label_camera_matrix)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_dist_coeffs = QtWidgets.QLabel(self.groupBox_3)
        self.label_dist_coeffs.setObjectName("label_dist_coeffs")
        self.verticalLayout.addWidget(self.label_dist_coeffs)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.label_error_intrinsic = QtWidgets.QLabel(self.groupBox_3)
        self.label_error_intrinsic.setObjectName("label_error_intrinsic")
        self.horizontalLayout_3.addWidget(self.label_error_intrinsic)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_new_matrix = QtWidgets.QLabel(self.groupBox_3)
        self.label_new_matrix.setObjectName("label_new_matrix")
        self.verticalLayout.addWidget(self.label_new_matrix)
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setObjectName("label_25")
        self.verticalLayout.addWidget(self.label_25)
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.label_rotation_matrix = QtWidgets.QLabel(self.groupBox_3)
        self.label_rotation_matrix.setObjectName("label_rotation_matrix")
        self.verticalLayout.addWidget(self.label_rotation_matrix)
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.label_translation_vect = QtWidgets.QLabel(self.groupBox_3)
        self.label_translation_vect.setObjectName("label_translation_vect")
        self.verticalLayout.addWidget(self.label_translation_vect)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_2.addWidget(self.label_28)
        self.label_error_extrinsic = QtWidgets.QLabel(self.groupBox_3)
        self.label_error_extrinsic.setObjectName("label_error_extrinsic")
        self.horizontalLayout_2.addWidget(self.label_error_extrinsic)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_9.addWidget(self.groupBox_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.push_button_qv4l2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.push_button_qv4l2.setObjectName("push_button_qv4l2")
        self.gridLayout_9.addWidget(self.push_button_qv4l2, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 5, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_5)
        self.graphics_view_cam = PlotWidget(self.splitter)
        self.graphics_view_cam.setObjectName("graphics_view_cam")
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_cam, "")
        self.tab_sys = QtWidgets.QWidget()
        self.tab_sys.setObjectName("tab_sys")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_sys)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphics_view_sys_1 = PlotWidget(self.tab_sys)
        self.graphics_view_sys_1.setObjectName("graphics_view_sys_1")
        self.gridLayout_3.addWidget(self.graphics_view_sys_1, 0, 0, 1, 1)
        self.graphics_view_sys_2 = PlotWidget(self.tab_sys)
        self.graphics_view_sys_2.setObjectName("graphics_view_sys_2")
        self.gridLayout_3.addWidget(self.graphics_view_sys_2, 0, 1, 1, 1)
        self.graphics_view_sys_3 = PlotWidget(self.tab_sys)
        self.graphics_view_sys_3.setObjectName("graphics_view_sys_3")
        self.gridLayout_3.addWidget(self.graphics_view_sys_3, 1, 0, 1, 1)
        self.graphics_view_sys_4 = PlotWidget(self.tab_sys)
        self.graphics_view_sys_4.setObjectName("graphics_view_sys_4")
        self.gridLayout_3.addWidget(self.graphics_view_sys_4, 1, 1, 1, 1)
        self.tab_widget.addTab(self.tab_sys, "")
        self.tab_plot = QtWidgets.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_plot)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter_3 = QtWidgets.QSplitter(self.tab_plot)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.splitter_3)
        self.scrollArea_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 228, 604))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_10.addWidget(self.checkBox_5, 5, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_10.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_10.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_10.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_10.addWidget(self.checkBox_4, 4, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_10.addWidget(self.checkBox_6, 3, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 3, 0, 1, 2)
        self.pb_clear_all = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_clear_all.setObjectName("pb_clear_all")
        self.gridLayout_6.addWidget(self.pb_clear_all, 2, 0, 1, 2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.combo_box_color = QtWidgets.QComboBox(self.groupBox_6)
        self.combo_box_color.setObjectName("combo_box_color")
        self.combo_box_color.addItem("")
        self.combo_box_color.addItem("")
        self.combo_box_color.addItem("")
        self.combo_box_color.addItem("")
        self.gridLayout_12.addWidget(self.combo_box_color, 0, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_6)
        self.label_27.setObjectName("label_27")
        self.gridLayout_12.addWidget(self.label_27, 0, 0, 1, 1)
        self.pb_show_results = QtWidgets.QPushButton(self.groupBox_6)
        self.pb_show_results.setObjectName("pb_show_results")
        self.gridLayout_12.addWidget(self.pb_show_results, 1, 0, 1, 2)
        self.gridLayout_6.addWidget(self.groupBox_6, 1, 0, 1, 2)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget = QtWidgets.QWidget(self.splitter_3)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_layout_plot3d = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_layout_plot3d.setContentsMargins(0, 0, 0, 0)
        self.grid_layout_plot3d.setObjectName("grid_layout_plot3d")
        self.gridLayout_5.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_plot, "")
        self.scrollArea = QtWidgets.QScrollArea(self.splitter_2)
        self.scrollArea.setMaximumSize(QtCore.QSize(400, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 363, 1135))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 4, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 2, 0, 1, 1)
        self.lb_point_indicator = QtWidgets.QLabel(self.groupBox_4)
        self.lb_point_indicator.setText("")
        self.lb_point_indicator.setObjectName("lb_point_indicator")
        self.gridLayout_7.addWidget(self.lb_point_indicator, 7, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 16, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 22, 0, 1, 1)
        self.pb_rotate = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_rotate.setObjectName("pb_rotate")
        self.gridLayout_7.addWidget(self.pb_rotate, 20, 0, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 14, 0, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 12, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 8, 0, 1, 2)
        self.pb_start_extrinsic = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_start_extrinsic.setObjectName("pb_start_extrinsic")
        self.gridLayout_7.addWidget(self.pb_start_extrinsic, 5, 0, 1, 1)
        self.sb_delay_extrinsic = QtWidgets.QSpinBox(self.groupBox_4)
        self.sb_delay_extrinsic.setProperty("value", 5)
        self.sb_delay_extrinsic.setObjectName("sb_delay_extrinsic")
        self.gridLayout_7.addWidget(self.sb_delay_extrinsic, 2, 1, 1, 1)
        self.pb_calib_extrinsic = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_calib_extrinsic.setObjectName("pb_calib_extrinsic")
        self.gridLayout_7.addWidget(self.pb_calib_extrinsic, 13, 0, 1, 2)
        self.pb_stop_extrinsic = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_stop_extrinsic.setObjectName("pb_stop_extrinsic")
        self.gridLayout_7.addWidget(self.pb_stop_extrinsic, 5, 1, 1, 1)
        self.combo_box_method = QtWidgets.QComboBox(self.groupBox_4)
        self.combo_box_method.setObjectName("combo_box_method")
        self.combo_box_method.addItem("")
        self.combo_box_method.addItem("")
        self.gridLayout_7.addWidget(self.combo_box_method, 10, 1, 1, 1)
        self.sb_light_radius = QtWidgets.QSpinBox(self.groupBox_4)
        self.sb_light_radius.setMinimum(1)
        self.sb_light_radius.setMaximum(99)
        self.sb_light_radius.setSingleStep(2)
        self.sb_light_radius.setProperty("value", 5)
        self.sb_light_radius.setDisplayIntegerBase(10)
        self.sb_light_radius.setObjectName("sb_light_radius")
        self.gridLayout_7.addWidget(self.sb_light_radius, 3, 1, 1, 1)
        self.cb_video_recording = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb_video_recording.setObjectName("cb_video_recording")
        self.gridLayout_7.addWidget(self.cb_video_recording, 4, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 1, 0, 1, 2)
        self.pb_save_points = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_save_points.setObjectName("pb_save_points")
        self.gridLayout_7.addWidget(self.pb_save_points, 6, 0, 1, 1)
        self.pb_load_points = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_load_points.setObjectName("pb_load_points")
        self.gridLayout_7.addWidget(self.pb_load_points, 6, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 10, 0, 1, 1)
        self.dsb_first_height = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.dsb_first_height.setSingleStep(0.01)
        self.dsb_first_height.setProperty("value", 1.0)
        self.dsb_first_height.setObjectName("dsb_first_height")
        self.gridLayout_7.addWidget(self.dsb_first_height, 22, 1, 1, 1)
        self.dsp_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.dsp_threshold.setDecimals(4)
        self.dsp_threshold.setMinimum(0.0001)
        self.dsp_threshold.setMaximum(3.0)
        self.dsp_threshold.setSingleStep(0.0001)
        self.dsp_threshold.setProperty("value", 0.01)
        self.dsp_threshold.setObjectName("dsp_threshold")
        self.gridLayout_7.addWidget(self.dsp_threshold, 12, 1, 1, 1)
        self.pb_bundle_adjustment = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_bundle_adjustment.setObjectName("pb_bundle_adjustment")
        self.gridLayout_7.addWidget(self.pb_bundle_adjustment, 15, 0, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 21, 0, 1, 2)
        self.pb_scale = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_scale.setObjectName("pb_scale")
        self.gridLayout_7.addWidget(self.pb_scale, 23, 0, 1, 2)
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 7, 0, 1, 1)
        self.pb_save_extrinsic = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_save_extrinsic.setObjectName("pb_save_extrinsic")
        self.gridLayout_7.addWidget(self.pb_save_extrinsic, 0, 0, 1, 1)
        self.pb_load_extrinsic = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_load_extrinsic.setObjectName("pb_load_extrinsic")
        self.gridLayout_7.addWidget(self.pb_load_extrinsic, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 11, 0, 1, 1)
        self.dsp_prob = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.dsp_prob.setDecimals(3)
        self.dsp_prob.setMaximum(0.999)
        self.dsp_prob.setSingleStep(0.001)
        self.dsp_prob.setProperty("value", 0.999)
        self.dsp_prob.setObjectName("dsp_prob")
        self.gridLayout_7.addWidget(self.dsp_prob, 11, 1, 1, 1)
        self.pb_start_ground = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_start_ground.setObjectName("pb_start_ground")
        self.gridLayout_7.addWidget(self.pb_start_ground, 17, 0, 1, 1)
        self.pb_stop_ground = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_stop_ground.setObjectName("pb_stop_ground")
        self.gridLayout_7.addWidget(self.pb_stop_ground, 17, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.combo_box_video = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        self.combo_box_video.setMinimumSize(QtCore.QSize(0, 0))
        self.combo_box_video.setObjectName("combo_box_video")
        self.combo_box_video.addItem("")
        self.combo_box_video.addItem("")
        self.combo_box_video.addItem("")
        self.combo_box_video.addItem("")
        self.combo_box_video.addItem("")
        self.gridLayout_8.addWidget(self.combo_box_video, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_35 = QtWidgets.QLabel(self.groupBox_5)
        self.label_35.setObjectName("label_35")
        self.gridLayout_11.addWidget(self.label_35, 0, 0, 1, 2)
        self.dsb_filter = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.dsb_filter.setMaximum(1.0)
        self.dsb_filter.setSingleStep(0.01)
        self.dsb_filter.setProperty("value", 0.9)
        self.dsb_filter.setObjectName("dsb_filter")
        self.gridLayout_11.addWidget(self.dsb_filter, 9, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_5)
        self.label_36.setObjectName("label_36")
        self.gridLayout_11.addWidget(self.label_36, 3, 0, 1, 2)
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setObjectName("label_29")
        self.gridLayout_11.addWidget(self.label_29, 1, 0, 1, 1)
        self.pb_start_mocap = QtWidgets.QPushButton(self.groupBox_5)
        self.pb_start_mocap.setObjectName("pb_start_mocap")
        self.gridLayout_11.addWidget(self.pb_start_mocap, 12, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setObjectName("label_32")
        self.gridLayout_11.addWidget(self.label_32, 8, 0, 1, 1)
        self.pb_stop_mocap = QtWidgets.QPushButton(self.groupBox_5)
        self.pb_stop_mocap.setObjectName("pb_stop_mocap")
        self.gridLayout_11.addWidget(self.pb_stop_mocap, 12, 1, 1, 1)
        self.sb_dist_threshold = QtWidgets.QSpinBox(self.groupBox_5)
        self.sb_dist_threshold.setMinimum(1)
        self.sb_dist_threshold.setMaximum(100)
        self.sb_dist_threshold.setProperty("value", 20)
        self.sb_dist_threshold.setObjectName("sb_dist_threshold")
        self.gridLayout_11.addWidget(self.sb_dist_threshold, 1, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 4, 0, 1, 1)
        self.dsb_pose_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.dsb_pose_threshold.setMaximum(1.0)
        self.dsb_pose_threshold.setSingleStep(0.01)
        self.dsb_pose_threshold.setProperty("value", 0.5)
        self.dsb_pose_threshold.setObjectName("dsb_pose_threshold")
        self.gridLayout_11.addWidget(self.dsb_pose_threshold, 4, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_11.addWidget(self.label_31, 5, 0, 1, 1)
        self.dsb_keypoint_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.dsb_keypoint_threshold.setMaximum(1.0)
        self.dsb_keypoint_threshold.setSingleStep(0.01)
        self.dsb_keypoint_threshold.setProperty("value", 0.2)
        self.dsb_keypoint_threshold.setObjectName("dsb_keypoint_threshold")
        self.gridLayout_11.addWidget(self.dsb_keypoint_threshold, 5, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_11.addWidget(self.label_33, 9, 0, 1, 1)
        self.dsb_tracking_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.dsb_tracking_threshold.setMaximum(10.0)
        self.dsb_tracking_threshold.setSingleStep(0.1)
        self.dsb_tracking_threshold.setProperty("value", 1.0)
        self.dsb_tracking_threshold.setObjectName("dsb_tracking_threshold")
        self.gridLayout_11.addWidget(self.dsb_tracking_threshold, 8, 1, 1, 1)
        self.sb_min_cam = QtWidgets.QSpinBox(self.groupBox_5)
        self.sb_min_cam.setMinimum(2)
        self.sb_min_cam.setMaximum(4)
        self.sb_min_cam.setProperty("value", 2)
        self.sb_min_cam.setObjectName("sb_min_cam")
        self.gridLayout_11.addWidget(self.sb_min_cam, 2, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_5)
        self.label_37.setObjectName("label_37")
        self.gridLayout_11.addWidget(self.label_37, 7, 0, 1, 2)
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setObjectName("label_34")
        self.gridLayout_11.addWidget(self.label_34, 2, 0, 1, 1)
        self.combo_box_models = QtWidgets.QComboBox(self.groupBox_5)
        self.combo_box_models.setObjectName("combo_box_models")
        self.combo_box_models.addItem("")
        self.combo_box_models.addItem("")
        self.combo_box_models.addItem("")
        self.gridLayout_11.addWidget(self.combo_box_models, 6, 0, 1, 2)
        self.cb_record_mocap = QtWidgets.QCheckBox(self.groupBox_5)
        self.cb_record_mocap.setObjectName("cb_record_mocap")
        self.gridLayout_11.addWidget(self.cb_record_mocap, 10, 0, 1, 2)
        self.gridLayout_8.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.status_bar = QtWidgets.QStatusBar(MainWindow)
        self.status_bar.setObjectName("status_bar")
        MainWindow.setStatusBar(self.status_bar)

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(2)
        self.combo_box_video.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Intrinsic calibration"))
        self.label_5.setText(_translate("MainWindow", "Grid width:"))
        self.pb_calib_intrinsic.setText(_translate("MainWindow", "Calibrate intrinsic parameters"))
        self.label_4.setText(_translate("MainWindow", "Number of pics:"))
        self.label_3.setText(_translate("MainWindow", "Delay: (sec)"))
        self.label_6.setText(_translate("MainWindow", "Grid height:"))
        self.pb_save_intrinsic.setText(_translate("MainWindow", "Save"))
        self.pb_load_intrinsic.setText(_translate("MainWindow", "Load"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Camera parameters"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Intrinsic parameters</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Camera matrix:"))
        self.label_camera_matrix.setText(_translate("MainWindow", "- - -"))
        self.label_9.setText(_translate("MainWindow", "Distorition:"))
        self.label_dist_coeffs.setText(_translate("MainWindow", "- - -"))
        self.label_11.setText(_translate("MainWindow", "Error intrinsic:"))
        self.label_error_intrinsic.setText(_translate("MainWindow", "-"))
        self.label_8.setText(_translate("MainWindow", "New camera matrix:"))
        self.label_new_matrix.setText(_translate("MainWindow", "- - -"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Extrinsic parameters</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "Rotation matrix:"))
        self.label_rotation_matrix.setText(_translate("MainWindow", "- - -"))
        self.label_24.setText(_translate("MainWindow", "Translation vector:"))
        self.label_translation_vect.setText(_translate("MainWindow", "- - -"))
        self.label_28.setText(_translate("MainWindow", "Error extrinsic:"))
        self.label_error_extrinsic.setText(_translate("MainWindow", "-"))
        self.label_2.setText(_translate("MainWindow", "Choose camera:"))
        self.push_button_qv4l2.setText(_translate("MainWindow", "configure camera with qv4l2"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_cam), _translate("MainWindow", "Camera settings"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_sys), _translate("MainWindow", "System configuration"))
        self.groupBox.setTitle(_translate("MainWindow", "Show/Hide"))
        self.checkBox_5.setText(_translate("MainWindow", "Human lines"))
        self.checkBox_2.setText(_translate("MainWindow", "Axises"))
        self.checkBox.setText(_translate("MainWindow", "Grid"))
        self.checkBox_3.setText(_translate("MainWindow", "Cameras"))
        self.checkBox_4.setText(_translate("MainWindow", "Human points"))
        self.checkBox_6.setText(_translate("MainWindow", "Calibration points"))
        self.pb_clear_all.setText(_translate("MainWindow", "Clear All"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Calibration results"))
        self.combo_box_color.setItemText(0, _translate("MainWindow", "error groups"))
        self.combo_box_color.setItemText(1, _translate("MainWindow", "time"))
        self.combo_box_color.setItemText(2, _translate("MainWindow", "avg error"))
        self.combo_box_color.setItemText(3, _translate("MainWindow", "empty"))
        self.label_27.setText(_translate("MainWindow", "Coloring:"))
        self.pb_show_results.setText(_translate("MainWindow", "Show"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_plot), _translate("MainWindow", "3D plot"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Extrinsic calibration"))
        self.label_15.setText(_translate("MainWindow", "Delay: (sec)"))
        self.label_13.setText(_translate("MainWindow", "Radius:"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step 4: Rotate to ground</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "First cam height: (m)"))
        self.pb_rotate.setText(_translate("MainWindow", "Rotate"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step 3: Bundle adjustment</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "Threshold:"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step 2: Calculating extrinsic</span></p></body></html>"))
        self.pb_start_extrinsic.setText(_translate("MainWindow", "Start collecting"))
        self.pb_calib_extrinsic.setText(_translate("MainWindow", "Calibrate extrinsic parameters"))
        self.pb_stop_extrinsic.setText(_translate("MainWindow", "Stop collecting"))
        self.combo_box_method.setItemText(0, _translate("MainWindow", "LMEDS"))
        self.combo_box_method.setItemText(1, _translate("MainWindow", "RANSAC"))
        self.cb_video_recording.setText(_translate("MainWindow", "Video recording"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step 1: Collecting points</span></p></body></html>"))
        self.pb_save_points.setText(_translate("MainWindow", "Save points"))
        self.pb_load_points.setText(_translate("MainWindow", "Load points"))
        self.label_20.setText(_translate("MainWindow", "Method:"))
        self.pb_bundle_adjustment.setText(_translate("MainWindow", "Calculate bundle adjustment"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step 5: Scale</span></p></body></html>"))
        self.pb_scale.setText(_translate("MainWindow", "Scale"))
        self.label_26.setText(_translate("MainWindow", "Points available:"))
        self.pb_save_extrinsic.setText(_translate("MainWindow", "Save"))
        self.pb_load_extrinsic.setText(_translate("MainWindow", "Load"))
        self.label_12.setText(_translate("MainWindow", "Prob:"))
        self.pb_start_ground.setText(_translate("MainWindow", "Start collecting"))
        self.pb_stop_ground.setText(_translate("MainWindow", "Stop collecting"))
        self.combo_box_video.setItemText(0, _translate("MainWindow", "640x480@30 FPS"))
        self.combo_box_video.setItemText(1, _translate("MainWindow", "640x480@60 FPS"))
        self.combo_box_video.setItemText(2, _translate("MainWindow", "320x240@30 FPS"))
        self.combo_box_video.setItemText(3, _translate("MainWindow", "320x240@60 FPS"))
        self.combo_box_video.setItemText(4, _translate("MainWindow", "320x240@120 FPS"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Global camera settings</span></p></body></html>"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Mocap"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Reconstruction parameters</span></p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Pose estimator parameters</span></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "Distance threshold:"))
        self.pb_start_mocap.setText(_translate("MainWindow", "start"))
        self.label_32.setText(_translate("MainWindow", "Tracking threshold:"))
        self.pb_stop_mocap.setText(_translate("MainWindow", "stop"))
        self.label_30.setText(_translate("MainWindow", "Pose threshold:"))
        self.label_31.setText(_translate("MainWindow", "Keypoint threshold:"))
        self.label_33.setText(_translate("MainWindow", "Filter:"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Tracking parameters</span></p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "Min cam num:"))
        self.combo_box_models.setItemText(0, _translate("MainWindow", "mobilenet_v1_353x481"))
        self.combo_box_models.setItemText(1, _translate("MainWindow", "mobilenet_v1_481x641"))
        self.combo_box_models.setItemText(2, _translate("MainWindow", "mobilenet_v1_721x1281"))
        self.cb_record_mocap.setText(_translate("MainWindow", "Video recording"))

from pyqtgraph import PlotWidget
